-- ALTER TABLE ROUTES AUTO_INCREMENT = 101;

-- ALTER TABLE TRAINS AUTO_INCREMENT = 10001;
ALTER TABLE routes AUTO_INCREMENT = 101;

-- Train table schema for MySQL
ALTER TABLE trains AUTO_INCREMENT = 10001;